server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /springboot-mybatis

spring:

  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: update

  mvc:
    view:

      prefix: /WEB-INF/jsp/

      suffix: .jsp

  spring:
     freemarker:
         request-context-attribute: req  #req访问request
         suffix: .html  #后缀名
         content-type: text/html
         enabled: true
         cache: false #缓存配置
         template-loader-path: classpath:/templates/ #模板加载路径 按需配置
         charset: UTF-8 #编码格式
         settings:
           number_format: '0.##'   #数字格式化，无小数点
     redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-idle: 300
            max-active: 600
            max-wait: 300
     data:
         mongodb:
           host: localhost
           port: 27017
           database: 1801a


